### ISSUE TITLE
lunching JCUDA

### ISSUE THREAD

**Issue by zakiournani** [jcuda/jcuda#1]
hello, I'am having a big issue lunching a java program using JCUDA, i did the installation , all paths are well sets, the test program of JCUDA compile without problems, but when i execute i got this 

Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "JCudaRuntime-linux-x86_64" with base name "JCudaRuntime"
Operating system name: Linux
Architecture         : amd64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libJCudaRuntime-linux-x86_64.so'
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	at jcuda.runtime.JCuda.initialize(JCuda.java:380)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:367)
	at JCudaRuntimeTest.main(JCudaRuntimeTest.java:9)
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: /home/zournani/JCuda/libJCudaRuntime-linux-x86_64.so: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /home/zournani/JCuda/libJCudaRuntime-linux-x86_64.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
	at jcuda.runtime.JCuda.initialize(JCuda.java:380)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:367)
	at JCudaRuntimeTest.main(JCudaRuntimeTest.java:9)

	at jcuda.LibUtils.loadLibrary(LibUtils.java:128)
	at jcuda.runtime.JCuda.initialize(JCuda.java:380)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:367)
	at JCudaRuntimeTest.main(JCudaRuntimeTest.java:9)
am stuck with this problem for a week, please help

**Comment by jcuda** [comment]
The relevant part here is

> "version `GLIBC_2.14' not found"

which, when entered into search engine, brings some results. I have opened a thread at the forum for this, see https://forum.byte-welt.net/byte-welt-projekte-projects/jcuda/18546-unsatisfiedlinkerror-version-glibc_2-14-found.html?langid=2 (no registration required)

I don't consider this as an "issue" in the sense that it should be tracked here, so I'll close this for now. (If it turns out that the Linux binaries should be compiled against an older glibc version, then I'll consider reopening it, but in general, support questions should be asked via mail or the forum, and not through the issue tracker)

**Comment by zakiournani** [comment]
Thanks for your answer,
I believe that the problem is not due to my Glibc version (i have the
latest). i've already checked most of the related questions on the forums.
I'll try to find a way to solve it.
regards.

2016-02-22 16:37 GMT+01:00 Marco Hutter <notifications@github.com>:

**Comment by jcuda** [comment]
OK, I'll reopen this, and I have contacted the contributor of the Linux binaries - maybe he has an idea what might be wrong here.

**Comment by MHBishop** [comment]
Hi,

`java.lang.NullPointerException: No resource found with name '/lib/libJCudaRuntime-linux-x86_64.so'`

Is there a file named libJCudaRuntime-linux-x86_64.so in your /lib directory?

**Comment by zakiournani** [comment]
Hi,
I added the path to the libraries in LD_lib_path . i also copied the files
to /lib but that didn't work. What i am going to try next is ti rebuild the
source code on my computer and see if this is due to the glibc version or
something else.
I will inform you that whould work.
Thaks.

**Comment by zakiournani** [comment]
Hi,
The problem have been solved, before attemping to rebuild the source. i
tried to replace the jar files and the so files.
Apparently either the  jcuda...JAR or the Jlibcuda...so was corrupted
durring the download or th SSH cp (i work on a distant server).
I just replaced the files and it seems to work, next time i must do a MD5
check.
thanks for helping and for your time. the topic may be closed.

2016-02-22 23:56 GMT+01:00 Zaki OURNANI <bz_ournani@esi.dz>:

> Hi,
> I added the path to the libraries in LD_lib_path . i also copied the files
> to /lib but that didn't work. What i am going to try next is ti rebuild the
> source code on my computer and see if this is due to the glibc version or
> something else.
> I will inform you that whould work.
> Thaks.
>

**Comment by jcuda** [comment]
@MHBishop Probably I should try to make this clearer. The message says 
`Stack trace from the attempt to load the library as a resource:` and
`Stack trace from the attempt to load the library as a file:` 
but I agree that this may not perfecly make clear what is happening there. Namely, that the `LibUtils` class tries to load the library in two ways: 

- First, it tries to load the library as a resource, directly from the JAR file. (This is not yet fully/officially supported, but one important step on the way of bringing JCuda properly into Maven Central - and to make deployment easier in general). 
- If it can *not* load the library as a resource, it tries to load the library as a file (from the `java.library.path`). This is the default way of loading the libraries, and relevant part here. This is where the `GLIBC_2.14` error message comes from.

However, it seems that the reason now only was file that was corrupted during the download, so I'll close this one.
