### ISSUE TITLE
Extend and update getByteBuffer method

### ISSUE THREAD

**Issue by jcuda** [jcuda/jcuda#11]
The current implementation of `Pointer#getByteBuffer` expects a `byteOffset` and a `byteLength` parameter. There should probably be a parameterless convenience method that returns a slice of the internal byte buffer with `position=0` and `limit=capacity()`, representing the full buffer.

Additionally, the `getByteBuffer` method currently returns a byte buffer with unspecified byte order. (By default, it will be `BIG_ENDIAN`, but this is not specified). This *might* be changed so that it will always return the byte buffer in *native* byte order (which will usually be `LITTLE_ENDIAN`). 

The problem here is that this would be a change that is not backward compatible. It **might**, however, be justified to change it and let it be the native byte order from now on, considering that the byte order was not specified until now, and everybody who used the byte buffer without explicitly setting the byte order relied on unspecified behavior anyhow. 

If this is changed, it will have to be pointed out prominently in the change logs.

**Comment by jcuda** [comment]
As proposed in https://forum.byte-welt.net/t/pointer-buffer-should-have-byteorder-little-endian/19508/3 , the implementation could be thread-safe and safe regarding the offsets by implementing it as

    ByteBuffer byteBuffer = ((ByteBuffer)buffer).slice();
    byteBuffer.limit(Math.toIntExact(byteOffset + byteSize));
    byteBuffer.position(Math.toIntExact(byteOffset));

**Comment by blueberry** [comment]
It is probably worth considering that Nvidia (and AMD) GPUs are LITTLE_ENDIAN, so IMHO that should be the default.

**Comment by jcuda** [comment]
Using the `nativeOrder()` certainly makes sense. In fact, I occasionally stumbled over the (nowadays somewhat unusual) `BIG_ENDIAN` being the default, and wondered why they did this... 

<sub>(This was an attempt to blame the Sun/Oracle people ;-) )</sub>

It would have made even *more* sense to do this right in the beginning, when the method was implemented. As mentioned above (and in the [forum thread](https://forum.byte-welt.net/t/pointer-buffer-should-have-byteorder-little-endian/19508/2) ), changing this *now* might be incompatible.

But although I'm always hesitant do do changes like this, here, it may be justified: Most users probably already *did* set the byte order manually. And they did this (or should have done this) because until now, the byte order of the returned buffer was not *specified*. 

The advantage of specifying it now to be the `nativeOrder()` seems to outweigh the slight possibility of an incompatibiliy, especially when it's pointed out in the change log. 



 - mainly because the usual usage patterns likely involved setting the byte order anyhow

**Comment by almson** [comment]
`BIG_ENDIAN` is the default probably because it is the "network" byte order used by many protocols such as TCP/IP.

File I/O defaults to whatever is the system's code page, while NIO standardizes on BIG_ENDIAN. The JDK guys made the wrong choice both times :)
