### ISSUE TITLE
jcuda library absent

### ISSUE THREAD

**Issue by benoitbenoit** [jcuda/jcuda#13]
Hello,
I created a project (netbeans) and added in my pom.xml file all jcuda dependencies. That's really great, thank you for this development.
However, all the library are compiled (jcublas, jcufft ...) except "jcuda". Due to that, I can not run my program (JCudaRuntime library not found). 
Did I missed something ?
![cudaquestion](https://user-images.githubusercontent.com/16206262/33434054-52148a9e-d5de-11e7-81b9-2153b2b72477.png)
Thank you for your response
Ben

**Comment by jcuda** [comment]
The files are listed at http://central.maven.org/maven2/org/jcuda/jcuda-natives/0.8.0/

The file that you highlighted is http://central.maven.org/maven2/org/jcuda/jcuda-natives/0.8.0/jcuda-natives-0.8.0-linux-x86_64.jar , and it seems to contain the `lib` folder with the native library.

I'm not entirely sure what went wrong here. As a naive quick shot: You could consider deleting the file (maybe even the whole `jcuda` path in your `.m2` folder) and pull a fresh copy. If this doesn't solve the issue, we'll have to investigate this further...

**Comment by benoitbenoit** [comment]
Thanks. 
Actually, if I replace cuda-natives-0.8.0-linux-x86_64.jar in .m2 folder, then it works well. 
I just asked the question because I was surprised to have to do that to solve the problem. 
I thought I did something wrong.

**Comment by jcuda** [comment]
In the best case, it was just some Maven hiccup - although it's strange that the JAR was *there* but did not contain the library ... 

I'll leave this issue open for a while, just to keep an eye on it...
