### ISSUE TITLE
Jetson Support (CUDA 8)

### ISSUE THREAD

**Issue by evbarnett** [jcuda/jcuda#15]
We are trying to build JCuda on a Jetson TX1 running CUDA 8. Do you have any advice?

We were following building instructions from [here](https://github.com/jcuda/jcuda-main/blob/master/BUILDING.md).

And we had to make the changes from [this commit](https://github.com/jcuda/jcuda/commit/d909b6f9dcbc2952da5d409b4e16ebe61421bea6) also, since it hasn't made it's way to the version-0.8.0 tag yet.

The first step of compilation (compiling the *.so) works, but when compiling the jars we get errors during testing.

The error we get is:

> jcuda.CudaException: Could not create ptx file

I've attached the full building / error messages.
[JcudaMvnErrorPTX.txt](https://github.com/jcuda/jcuda/files/1687764/JcudaMvnErrorPTX.txt)

Thanks for your help!

**Comment by evbarnett** [comment]
Nevermind, I think we fixed the problem. It was caused by a improper PATH to nvcc.

If you want the compiled jars to include on maven, let me know. I'm closing the issue.

**Comment by jcuda** [comment]
Except for some contributions (like the commit that you linked to) I don't have any practical experience with Jetson. So the question may sound naive, but ... is there an infrastructure that would benefit from the natives being on Maven Central? I mean, it should be possible to add the JARs containing the natives for 0.8.0, so if you think that this could be useful, I could create the bundle and upload it.
