### ISSUE TITLE
Copying to constant memory in CUDA 8?

### ISSUE THREAD

**Issue by zealng** [jcuda/jcuda#17]
Hello,

**Is it currently possible to copy from the host to device constant memory?**
I am currently using CUDA 8.0.

When I attempted to do so, I tried using
1) JCuda.cudaMemcpyToSymbol
2) JCuda.cudaGetSymbolAddress, then jcuda.runtime.cuMemcpyHtoD.
Both JCuda.* functions threw a java.lang.UnsupportedOperationException, saying "This function is no longer supported as of CUDA 5.0".
I see on jcuda.org that these functions are not supported.

In any case, is there a way around this, so that it is possible to copy data to device constant memory?

Thanks in advance.

**Comment by jcuda** [comment]
The constant memory is declared together with the kernel. Or more generally: Inside a `.cu` file that is compiled into a `.PTX` or `.CUBIN` file, which can then be loaded as a `CUmodule`.

From such a module, you can obtain a pointer to the constant memory using `cuModuleGetGlobal`:

    // Obtain the pointer to the constant memory, and print some info
    CUdeviceptr constantMemoryPointer = new CUdeviceptr();
    long constantMemorySizeArray[] = { 0 };
    cuModuleGetGlobal(constantMemoryPointer, constantMemorySizeArray, 
        module, "constantMemoryData");
    int constantMemorySize = (int)constantMemorySizeArray[0];
        
    System.out.println("constantMemoryPointer: " + constantMemoryPointer);
    System.out.println("constantMemorySize: " + constantMemorySize);

I added a (small, but complete) example in this commit: https://github.com/jcuda/jcuda-samples/commit/2e6e62d0a463a6ebca6ca230bd015f96b955f08e

**Comment by zealng** [comment]
Ah, thanks! That was exactly the functionality I was looking for. :)

It's unfortunate that CUDA documentation makes no clear reference that that function can be used to set constant memory.
