### ISSUE TITLE
cuMemAlloc & cuMemcpyHtoD doesn't work

### ISSUE THREAD

**Issue by Jet132** [jcuda/jcuda#20]
### I'm trying to get a programm for matrix multiplication, addition and with sigmoid-function to work.

I made a test, where i set everything up and run it successfuly.
Then I implemented that into the actual programm and it stopped working.
I looked at everything and both functions cuMemAlloc and cuMemcpyHtoD return 201 and the CUdeviceptr that they should define has still an empty pointer.

When i run the programm it doesn't give an error, but the function:

 ```
float[] layer(float[] input, float[] weights, float[] baises, int[] wd) {

		// Allocate the device input data, and copy the
		// host input data to the device
		CUdeviceptr inputInput = new CUdeviceptr();
		cuMemAlloc(inputInput,input.length * Sizeof.FLOAT);
		cuMemcpyHtoD(inputInput, Pointer.to(input), input.length * Sizeof.FLOAT);

		CUdeviceptr inputWeights = new CUdeviceptr();
		cuMemAlloc(inputWeights, weights.length * Sizeof.FLOAT);
		cuMemcpyHtoD(inputWeights, Pointer.to(weights), weights.length * Sizeof.FLOAT);

		CUdeviceptr inputBaises = new CUdeviceptr();
		cuMemAlloc(inputBaises, baises.length * Sizeof.FLOAT);
		cuMemcpyHtoD(inputBaises, Pointer.to(baises), baises.length * Sizeof.FLOAT);

		// Allocate device output memory
		CUdeviceptr deviceOutput = new CUdeviceptr();
		cuMemAlloc(deviceOutput, baises.length * Sizeof.FLOAT);

		// Set up the kernel parameters: A pointer to an array
		// of pointers which point to the actual values.
		Pointer kernelParameters = Pointer.to(
                                Pointer.to(new int[] { wd[0] }), 
                                Pointer.to(new int[] { wd[1] }),
				Pointer.to(inputInput), 
                                Pointer.to(inputWeights), 
                                Pointer.to(inputBaises), 
                                Pointer.to(deviceOutput));

		// Call the kernel function.
		int blockSizeX = 1000;
		int gridSizeX = (int) Math.ceil((double) baises.length / blockSizeX);
		cuLaunchKernel(AIEngine.LayerFunction, 
                                gridSizeX, 1, 1, // Grid dimension
				blockSizeX, 1, 1, // Block dimension
				0, null, // Shared memory size and stream
				kernelParameters, null // Kernel- and extra parameters
		);

		float hostOutput[] = new float[baises.length];
		cuMemcpyDtoH(Pointer.to(hostOutput), deviceOutput, baises.length * Sizeof.FLOAT);

		// Clean up.
		cuMemFree(inputInput);
		cuMemFree(inputWeights);
		cuMemFree(inputBaises);
		cuMemFree(deviceOutput);
		return hostOutput;
	}
```
gives an empty array.

The kernel gets loaded in another class, but I already tried it in the same class and it didn't work.

thank you in advance

**Comment by jcuda** [comment]
(Did you set 
`JCudaDriver.setExceptionsEnabled(true);`
somewhere (e.g. in your `main`) to make sure that the error is caught as early as possible?)

Error code 201 means `CUDA_ERROR_INVALID_CONTEXT`. Could it be that this function is called in a separate thread, for which no CUDA context exists?

If this is not the case, it could be helpful to have a MCVE, but know that it can be difficult to extract one from a larger application. (My concern is that I could integrate the code that you posted into a MCVE, and see that `cuMemcpyHtoD` works in this case - there must be some other crucial difference that is relevant here...)

**Comment by Jet132** [comment]
I put
```
JCudaDriver.setExceptionsEnabled(true);
```
into the setup function and as you said it stated:
```
loadingException in thread "Timer-0" jcuda.CudaException: CUDA_ERROR_INVALID_CONTEXT

	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:337)
	at jcuda.driver.JCudaDriver.cuMemAlloc(JCudaDriver.java:3836)
	at GPUClasses.GPUAI.layer(GPUAI.java:60)
	at GPUClasses.GPUAI.run(GPUAI.java:50)
	at AI_Engine.AIEngine.runEngine(AIEngine.java:122)
	at Main.MainGameLoop$1.run(MainGameLoop.java:71)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
```
the program is in another thread, because i'm using ``` timer.scheduleAtFixedRate(); ```, but the setup get's executed in the same thread as the kernel. 

Here is the whole code: [https://github.com/Jet132/temp/tree/master/AI_Engine_6.1/src](url)
(main at **Main/MainGameLoop.java** / setup at **AI_Engine/AIEngine.java** / kernel function at **GPUClasses/GPUAI.java**)

I will try to move the kernel executing function to the main class and see if it will work.

btw. this is my first Cuda program, so i don't know how the context-thing workes

**Comment by Jet132** [comment]
instead of using a timer i just used a simple while loop and it worked

thanks!

**Comment by jcuda** [comment]
Some details of the context handling may be a bit difficult. But the *basic* pattern is quite simple. 

Some pseudocode:

    // Create a context on the main thread. This context will be "bound" to
    // the main thread. This means that all operations (e.g. memory allocations)
    // are done using THIS context
    cuInit(0);
    CUdevice device = new CUdevice();
    cuDeviceGet(device, 0);
    CUcontext context = new CUcontext();
    cuCtxCreate(context, 0, device);

    // Allocate some data. This also happens on the main thread,
    // and thus, the memory is specific for the context that was 
    // created above
    CUdeviceptr pointer = new CUdeviceptr();
    cuMemAlloc(pointer, 4);

    // Try to use the allocated memory in a different thread
    executeInOtherThread(() -> {
        cuMemcpyHtoD(pointer, Pointer.to(hostData), 4); // THIS WILL CRASH!
    });

The reason for why this will **not** work is: The `pointer` was allocated using the `context` which was created on the main thread. The new thread (which may, for example, be a thread that is used inside a `Timer`) does not have any `CUcontext` associated with it. 

More details about the context handling are, for example, explained at https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#context

The main thing that has to be done is to call `cuCtxSetCurrent` for the thread that will use the context:

    // Try to use the allocated memory in a different thread
    executeInOtherThread(() -> {

        // First, make sure that the context is the "current" context for this thread
        cuCtxSetCurrent(context);

        cuMemcpyHtoD(pointer, Pointer.to(hostData), 4); // This should work now
    });

# but note:

This is **only** a sketch! Of course, when you have multiple threads, you will need additional synchronization. For example, if you have code like this

    executeInThread_A(() -> {
        cuCtxSetCurrent(context);
        cuMemcpyHtoD(pointer, Pointer.to(hostData), 4); 
    });
    executeInThread_B(() -> {
        cuCtxSetCurrent(context);
        cuMemcpyHtoD(pointer, Pointer.to(hostData), 4); 
    });

then it is not clear in which order the threads execute these methods. If you're lucky, then it might work:



            Thread A            Thread B
          -------------------------------------
    Time  |  cuCtxSetCurrent     
      |   |  cuMemcpyHtoD 
      v   |                      cuCtxSetCurrent     
          |                      cuMemcpyHtoD 
    
but without additional synchronization, this might happen:
    
            Thread A            Thread B
          -------------------------------------
    Time  |  cuCtxSetCurrent     
      |   |                      cuCtxSetCurrent     
      v   |  cuMemcpyHtoD                         <- This will crash!                    
          |                      cuMemcpyHtoD 
    
So you have to think about which thread the `context` should belong to, and how to make sure that no other thread grabs this context in the meantime.

**Comment by Jet132** [comment]
Ah ok thanks

I was planning to make my program multithreaded to accelerate it even more, so this will probably be very helpful.

**Comment by jcuda** [comment]
Again, multiple contexts may be a bit tricky to handle, but with the basic idea of **"one context is bound to one thread**", the appropriate `cuCtxSetCurrent`  calls and associated synchronization, it's doable.

You may also want to have a look at https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#multiple-contexts 

(There are several resources about context handling out there - unfortunately, I cannot provide a "best practices" guide here in these issue comments)

Assuming that it's OK to close this issue (just comment + reopen if there is still an issue)

**Comment by Jet132** [comment]
Sorry that I have to reopen this issue, but after the last problem was fixed, I started optimizing the code and another problem appeared:
```
Exception in thread "main" jcuda.CudaException: CUDA_ERROR_ILLEGAL_ADDRESS
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:337)
	at jcuda.driver.JCudaDriver.cuMemFree(JCudaDriver.java:4022)
	at GPUClasses.GPUAI.layer(GPUAI.java:95)
	at GPUClasses.GPUAI.run(GPUAI.java:70)
	at AI_Engine.AIEngine.runEngine(AIEngine.java:122)
	at Main.MainGameLoop.run(MainGameLoop.java:68)
	at Main.MainGameLoop.main(MainGameLoop.java:48)

```
the strange thing is also that it doesn't occure on the first few "runs", it only comes after exactly `1525970000000` millisecounds, that's about 25'000 calles of ```run()``` (look at the code below).
Also only if it needs to calculate with an array of about the lenght 200.

To explain my changes, I first need to tell what the program actually should do.
If your familiar with neural networks, you will know that they have layers, which contain weights and baises.
You pass a input to the network and it gets passed through every layer (input*weights+baises) and the weights and baises don't change most of the time. 
So I made that those two are permenant on the gpu and only get exchanged if they get changed. Also i made so, that every output (except the last one) stays on the gpu so the next layer can directly use it.

here is the important code (exeption lines are marked with **//ERROR** and have the same exeption):
```
        private CUdeviceptr[] weightPointers;
	private CUdeviceptr[] baisesPointers;
	private CUdeviceptr temp;//the output of last layer

	public GPUAI(int Generationsteps, int[] layout) {

		weightPointers = new CUdeviceptr[weights.length];
		for (int i = 0; i < weights.length; i++) {
			weightPointers[i] = new CUdeviceptr();
			cuMemAlloc(weightPointers[i], weights[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(weightPointers[i], Pointer.to(weights[i]), weights[i].length * Sizeof.FLOAT);
		}

		baisesPointers = new CUdeviceptr[baises.length];
		for (int i = 0; i < baises.length; i++) {
			baisesPointers[i] = new CUdeviceptr();
			cuMemAlloc(baisesPointers[i], baises[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(baisesPointers[i], Pointer.to(baises[i]), baises[i].length * Sizeof.FLOAT);
		}
	}

	public void run() {
		temp = new CUdeviceptr();
		cuMemAlloc(temp, Inputs.length * Sizeof.FLOAT);
		cuMemcpyHtoD(temp, Pointer.to(Inputs), Inputs.length * Sizeof.FLOAT);

		int last_layer = Inputs.length;
		for (int i = 0; i < weights.length-1; i++) {

			layer(i, last_layer);
			last_layer = baises[i].length;
		}
		Outputs = final_layer(weights.length-1, last_layer);
	}

	void layer(int layer, int inputsize) {
		// Allocate device output memory
		CUdeviceptr deviceOutput = new CUdeviceptr();
		cuMemAlloc(deviceOutput, baises.length * Sizeof.FLOAT);
		// Set up the kernel parameters: A pointer to an array
		// of pointers which point to the actual values.
		Pointer kernelParameters = Pointer.to(
                                Pointer.to(new int[] { inputsize }),
				Pointer.to(new int[] { baises[layer].length }),
                                Pointer.to(temp), 
                                Pointer.to(weightPointers[layer]),
				Pointer.to(baisesPointers[layer]), 
                                Pointer.to(deviceOutput));

		// Call the kernel function.
		int blockSizeX = 1000;
		int gridSizeX = (int) Math.ceil((double) baises.length / blockSizeX);
		cuLaunchKernel(AIEngine.LayerFunction, 
                                gridSizeX, 1, 1, // Grid dimension
				blockSizeX, 1, 1, // Block dimension
				0, null, // Shared memory size and stream
				kernelParameters, null // Kernel- and extra parameters
		);

                cuMemFree(temp); //ERROR
		temp = deviceOutput;

	}

	float[] final_layer(int layer, int inputsize) {
		// Allocate device output memory
		CUdeviceptr deviceOutput = new CUdeviceptr();
		cuMemAlloc(deviceOutput, baises.length * Sizeof.FLOAT);
		// Set up the kernel parameters: A pointer to an array
		// of pointers which point to the actual values.
		Pointer kernelParameters = Pointer.to(
                                Pointer.to(new int[] { inputsize }),
				Pointer.to(new int[] { baises[layer].length }), 
                                Pointer.to(temp), 
                                Pointer.to(weightPointers[layer]),
				Pointer.to(baisesPointers[layer]), 
                                Pointer.to(deviceOutput));

		// Call the kernel function.
		int blockSizeX = 1024;
		int gridSizeX = (int) Math.ceil((double) baises.length / blockSizeX);
		cuLaunchKernel(AIEngine.LayerFunction, 
                                gridSizeX, 1, 1, // Grid dimension
				blockSizeX, 1, 1, // Block dimension
				0, null, // Shared memory size and stream
				kernelParameters, null // Kernel- and extra parameters
		);

		

		float hostOutput[] = new float[baises.length];
		cuMemcpyDtoH(Pointer.to(hostOutput), deviceOutput, baises.length * Sizeof.FLOAT); //ERROR
		
		cuMemFree(temp); //ERROR
		
		return hostOutput;
	}

	void setWeights(float[][] weights) {
		for (int i = 0; i < weightPointers.length; i++) {
			cuMemFree(weightPointers[i]);
		}
		weightPointers = new CUdeviceptr[weights.length];
		for (int i = 0; i < weights.length; i++) {
			weightPointers[i] = new CUdeviceptr();
			cuMemAlloc(weightPointers[i], weights[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(weightPointers[i], Pointer.to(weights[i]), weights[i].length * Sizeof.FLOAT);
		}
	}

	void setBaises(float[][] baises) {
		for (int i = 0; i < baisesPointers.length; i++) {
			cuMemFree(baisesPointers[i]);
		}
		baisesPointers = new CUdeviceptr[baises.length];
		for (int i = 0; i < baises.length; i++) {
			baisesPointers[i] = new CUdeviceptr();
			cuMemAlloc(baisesPointers[i], baises[i].length * Sizeof.FLOAT);
			cuMemcpyHtoD(baisesPointers[i], Pointer.to(baises[i]), baises[i].length * Sizeof.FLOAT);
		}
	}
```
