### ISSUE TITLE
JCuda Pointer vs CudaMallocHost

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda#26]
It looks like iplemented in JCuda memory allocation mechanism contradicts native Cuda Host memory allocation mechanism. It also will contradict Unified memory architecture. Host memory can be allocated using Cuda Malloc Host and access to allocated memory should be provided via Pointer abstraction primitievs:

Pointer constructor allocates memory
Pointer.readAs<type>(offsetInTypeUnit,sizeInTypeUnit) reads data directly
Pointer.writeAs<type>(offsetInTypeUnit,sizeinTypeUnit) writes data into allocatted memory directly
etc.
Every Thread pool executor or Function run can claim several memory regions for exclusive(?) use

**Comment by jcuda** [comment]
I appreciate feedback, but you have opened several issues that are not really "issues" (or might just be issues on you side - is the issue with the native libraries resolved now or not). If you have specific suggestions for improvement (or even specific issues pointing out what's wrong), then tell me. But for now, I'll close this one, pointing to the managed memory example that I already pointed to in the previous issue: https://github.com/jcuda/jcuda-samples/blob/master/JCudaSamples/src/main/java/jcuda/driver/samples/JCudaDriverUnifiedMemory.java#L62

**Comment by PavelSosin-320** [comment]
@jcuda Thanks! It looks like the solution.
Could you mark the branch as release and create **very short Wiki page** which describes 1) high level design 2) releases and release notes: which issues are solved and.how. 3) backlog, i.e. on which issue/feature you are working.
