### ISSUE TITLE
Bug: CUdevprop referenced in JCudaDriver doesn't exist

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda#30]
Another class with invalid class name cudaDeviceProp exists

**Comment by PavelSosin-320** [comment]
The same is for other driver api classes
And why all classes inheriting NativePointerObject must implement own toString() if NativePointerObject  can implement it once? Overriding of abstract(!) class methods assumes that final class implementation differs from the basic class implementation but keeps parent class method signature. Otherwise it is meaningless.

**Comment by jcuda** [comment]
`CUdevprop` is here: https://github.com/jcuda/jcuda/blob/master/JCudaJava/src/main/java/jcuda/driver/CUdevprop.java

`cudaDeviceProp` is here: https://github.com/jcuda/jcuda/blob/master/JCudaJava/src/main/java/jcuda/runtime/cudaDeviceProp.java

The `toString` implementations of the classes extending `NativePointerObject` contain the *class name*, for example, `CUevent` here:

    public String toString()
    {
        return "CUevent["+
            "nativePointer=0x"+Long.toHexString(getNativePointer())+"]";
    }

This *could* also be achieved with `return getClass().getSimpleName()+"[...]"`, but I don't think it's worth arguing about which is "better".

**Comment by PavelSosin-320** [comment]
In this case reuse of super.toString() looks reasonable: return getClass().getSimpleName + super.toString() ... I hope it will work with any "NativePointer" implementation because the value returned by toString() can be used only for logging. The real Java Comparable requires  **.equals()**. Any final Pointer class has to call **super.equals()**

**Comment by jcuda** [comment]
The advantage of saving the `Long.toHexString(getNativePointer())` part, while still having to create a `toString` for each class, does not seem worthwhile.

The concept of pointers and `equals` is difficult, indeed. There may be two pointers that point to the same memory location, but should not be considered as being `equals`. If you have an idea of how to solve this, let me know. But by the way: All this is totally unrelated to `Comparable`....

**Comment by PavelSosin-320** [comment]
1. There are 2 methods which any java class inherits from Object class:
hashCode() which makes any 2 objects potentially comparable because 2 equal hashCodes mean that 2 objects are the same object.
toString() which is based on hashCode() by default. The second one is used in console output and logging. It returns what developer wants to show on console. If developer wants to show string representation of platform dependend memory address it has to be implemented at hardware aware layer. At hardware unaware level, i.e. Jave code it is impossible.

**Comment by jcuda** [comment]
> 2 equal hashCodes mean that 2 objects are the same object.

That's wrong. Start here: http://www.angelikalanger.com/Articles/JavaSolutions/SecretsOfEquals/Equals.html

I know the purpose of `toString`. The current implementations print something that I'd consider as "useful": For any `NativePointerObject`, the string contains the *type*  and the *value* of the pointer. What should be added, removed or changed there?

**Comment by PavelSosin-320** [comment]
Hi Marco,
In exact definition your implementation of toString() returns stringified
value of long typed property representing memory pointer in your
implementation. For anybody else who use your implementation as black box
it is meaningless. Try to create meaningful unit test which tests this
method.
Any discussions of toString and hashCode meanings which preseed the current
Java specification are not relevant because Java developer has to align his
code with the current Java 9 spec, otherwise his code can be used by
anybody. Java is abstract language which doesn't expose any plaform
architecture details and code running on intel platform must run on ARM
platform without any #ifdef . For example, java nio, java concurrent, java
Future have dufferent immplementation on for every platform but strictly
the same API.  This is java portability!

**Comment by PavelSosin-320** [comment]
@P.S. Indeed, Java is very rigid in any aspect of platform dependencies and
any platform dependent component requires implementation based on Abstract
Factory and Provider patterns. For example, Since Libraries proxy native
code is platform dependent NVidia library proxies can't be instantiated
directly but via something based on Abstract Factory and platform dependent
Provider. I skatched very basic implementation - see attachement

**Comment by jcuda** [comment]
The purpose of printing the address is to be able to see whether a pointer is `NULL` or whether two pointers are different. Beyond that, it is a memory address, which does not have a meaning. Compare it to C...

    char *ch = "123";
    printf("%p\n",ch);     

this prints "anything", and likely a different value each time you run the program. Creating a unit test for `toString` (in the case of a pointer class, where the output is supposed to be a human-readable, informative string, that is likely to change during each execution) does not make any sense, at all.

I thought that I'm rather patient, but now I'm waiting for you to complain that JCuda does not run on AMD platforms \*rolls eyes\*. What's the point of all this?
