### ISSUE TITLE
Cuda Data types definition - there is no unsigned integer in Java!

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda#31]
CUDA_R_32U in cudaTypes enumeration contains definitions for CUDA_R_32U and CUDA_C_32U. Java has no unsigned integer type and never had it.  All integers i Java are signed. integer biwise arithmethics works on integer but ignores sign. Starting from Java 8 Integer class provides unsigned integer bitwise [arithmetics](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html) API. Also JNI has only jint type which can be cast to C ulong with certain pre-cautions.
Similary, it is impossible to pass from java to native code **int but there is no need to do it because JNI can return Integer object using 
```
jclass intClass = (*env)->FindClass(env, "java/lang/Integer");
if (intClass == NULL) {
    return NULL;
}
jmethodID init =  (*env)->GetMethodID(env, intClass, "intValue", "()I");
if (init == NULL) {
    return NULL;
}
jobject rc_obj = (*env)->NewObject(env, intClass, init, rc);
if (rc_obj == NULL) {
    return NULL;
}

return rc_obj;
```

**Comment by jcuda** [comment]
An outtake from one of the earliest specifications of [Oak](https://en.wikipedia.org/wiki/Oak_(programming_language)) : 

![OakUnsigned](https://user-images.githubusercontent.com/13698062/68308077-8725d580-00ac-11ea-980c-f1427ca60b51.png)

---

However: It is true that Java does not have `unsigned` types. The [unsigned conversion methods](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#toUnsignedLong-int-) (similar for `byte` and `short`) convert to the "next largest" type (that is, an unsigned `byte` will become a (signed) `short`, and an unsigned `short` will become a (signed) `int`).

But this is not relevant: Bits are just bits. They don't have an inherent meaning. Even though in Java, a certain bit pattern like `0xFFFFFF85` is **interpreted** as a signed value, the **same** bit pattern can be interpreted as an unsigned value:

    int javaInt = -123;          // 0xFFFFFF85
    int32_t cInt = 4294967173;   // 0xFFFFFF85
    uint32_t cuInt = 4294967173; // 0xFFFFFF85

The caller has to make sure to not mess things up here. Usually, the unsigned types are transferred to the device and used there. It does not matter that they *would* be interpreted as signed values in Java.

---

Again, mixing several unrelated comments (\*rolls eyes\*) : I don't know what the `int**` part is about. If there is an array of `int` values to be handled, or one argument is supposed to be used "by reference" (emulated with a pointer in plain C), then this is done using an array of `int` values or a `int*` pointer, respectively. The `Integer` object is totally unrelated to all that (and it's immutable for that matter...)

**Comment by PavelSosin-320** [comment]
Simply FYI https://github.com/mapbox/jni.hpp - It looks like solid solution
for backing Java objects by JNI objects. In other words, how to box
everything written in native code into Java objects.Since native object can
encapsulate any resource, including externalm i.e. Host memory, Device
memory, Librarym etc.  and Java objects lifecycle is managed by JVM  it
solves manual management of lifecycle issue.
Since java object can implement any useful Java interface and, even, Apache
commons Math Matrix classes it can provide binding for Apache Commons Math
library.
I can't imagine something more useful than this feature.
