### ISSUE TITLE
Can we rename the development branch to main?

### ISSUE THREAD

**Issue by j143** [jcuda/jcuda#35]
Hi Marco,

Some of the projects refer code from this repo.
Is it possible to change the branch name to something
that you prefer? (perhaps `main`!)

Thanks a lot and Regards,
Janardhan

**Comment by jcuda** [comment]
The branch was originally called `master`, and I don't see a reason to rename it.

**Comment by jcuda** [comment]
>  **git**: *(Britain, slang, derogatory)* A silly, incompetent, stupid, annoying or childish person (usually a man). 
>
> https://en.wiktionary.org/wiki/git

That sounds pretty offensive. But I won't urge the Git developers to change that name. And I won't rename the branch.
