### ISSUE TITLE
Where is Jcudpp?

### ISSUE THREAD

**Issue by wilgaboury** [jcuda/jcuda#36]
There is documentation about this library on the jcuda website but I cannot find it's source code or a way to add it to my project. Has it been discontinued?

**Comment by jcuda** [comment]
It has indeed be discontinued, for a variety of reasons. The main ones being

- The development of https://github.com/cudpp/cudpp itself seems to be discontinued (the last commit was ~5 years ago)
- Even in the "active" time of CUDPP, compiling CUDPP was quite a hassle

May I ask which functionality of CUDPP in particular you would be interested in?

**Comment by wilgaboury** [comment]
That makes sense, thank you for clearing that up for me. I was specifically interested in multiscan and some kind of sort.

**Comment by saudet** [comment]
> That makes sense, thank you for clearing that up for me. I was specifically interested in multiscan and some kind of sort.

@wilgaboury Those can be found in the [Thrust](https://thrust.github.io/) library, which we can use relatively easily from Java with JavaCPP:
https://github.com/bytedeco/javacpp/wiki/Interface-Thrust-and-CUDA

**Comment by jcuda** [comment]
Nothing to add here, closing
