### ISSUE TITLE
how to downlaod the libraries of CUDA 11.2

### ISSUE THREAD

**Issue by ShirelyI** [jcuda/jcuda#38]
Hi,
I met some wrong messages when I ran juicer.sh : HiCCUPS:GPUs are not installed so HiCCUPs cannot be run. Then I checked the version of my CUDA is 11.2 but the latest version is 10.1 in http://www.jcuda.org/downloads/downloads.html ,I'm wondering if it could run successfully in 10.1 version? and where can I download the native libraries?
Thanks 
Lily

**Comment by jcuda** [comment]
The libraries are no longer offered on the "Downloads" page of the website. (In fact, the whole website hasn't bee updated for a while now, to be honest).

The latest versions of JCuda are available in Maven Central. You can ...

- **(recommended:)** Declare them as a dependency of your Maven project 
- **(NOT recommended:)** Download the desired JAR files from https://repo1.maven.org/maven2/org/jcuda/ and manually add them to the classpath

The latter may be a bit of a hassle. For example, you'd need the `jcuda-11.2.0.jar` from https://repo1.maven.org/maven2/org/jcuda/jcuda/11.2.0/, and the `jcuda-natives-11.2.0-windows-x86_64.jar` from https://repo1.maven.org/maven2/org/jcuda/jcuda-natives/11.2.0/ (for Windows, for example).

In any case, the native libraries will be contained in the respective JAR files that have the part `...-natives` in their name.

**Comment by jcuda** [comment]
No further action here, closing
